#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────────────────────────────────
#  Health Dashboard — Interactive Setup
#
#  Modes:
#    ./setup.sh              Interactive — prompts for all values
#    ./setup.sh --post-deploy  Reads deploy output, fills API URL
# ─────────────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
XCCONFIG_FILE="$SCRIPT_DIR/HealthDashboard/UserConfig.xcconfig"
EXPORT_PLIST="$SCRIPT_DIR/HealthDashboard/ExportOptions.plist"
DEPLOY_CONFIG="$SCRIPT_DIR/aws-deploy/.deploy-config"

# ── Helpers ──────────────────────────────────────────────────────────

red()   { printf '\033[1;31m%s\033[0m\n' "$*"; }
green() { printf '\033[1;32m%s\033[0m\n' "$*"; }
blue()  { printf '\033[1;34m%s\033[0m\n' "$*"; }

die() { red "ERROR: $*" >&2; exit 1; }

prompt() {
    local var_name="$1" prompt_text="$2" default="${3:-}"
    local value
    if [[ -n "$default" ]]; then
        printf "%s [%s]: " "$prompt_text" "$default"
    else
        printf "%s: " "$prompt_text"
    fi
    read -r value
    value="${value:-$default}"
    if [[ -z "$value" ]]; then
        die "$var_name is required"
    fi
    eval "$var_name=\"\$value\""
}

validate_team_id() {
    if [[ ! "$1" =~ ^[A-Z0-9]{10}$ ]]; then
        die "Team ID must be exactly 10 alphanumeric characters (got: $1)"
    fi
}

validate_url() {
    if [[ ! "$1" =~ ^https?:// ]]; then
        die "URL must start with http:// or https:// (got: $1)"
    fi
}

# ── Load existing .env if present ────────────────────────────────────

load_env() {
    if [[ -f "$ENV_FILE" ]]; then
        set -a
        source "$ENV_FILE"
        set +a
    fi
}

# ── Generate xcconfig ───────────────────────────────────────────────

generate_xcconfig() {
    local bundle_id="$1" team_id="$2" api_url="$3" user_id="$4"
    local bg_task_id="${bundle_id}.healthsync"

    cat > "$XCCONFIG_FILE" <<XCEOF
// Auto-generated by setup.sh — do not edit manually
PRODUCT_BUNDLE_IDENTIFIER = ${bundle_id}
DEVELOPMENT_TEAM = ${team_id}
HD_API_BASE_URL = ${api_url}
HD_USER_ID = ${user_id}
HD_BG_TASK_ID = ${bg_task_id}
XCEOF

    green "Generated: $XCCONFIG_FILE"
}

# ── Generate ExportOptions.plist ────────────────────────────────────

generate_export_plist() {
    local team_id="$1"

    cat > "$EXPORT_PLIST" <<PLISTEOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>method</key>
	<string>app-store-connect</string>
	<key>teamID</key>
	<string>${team_id}</string>
	<key>signingStyle</key>
	<string>automatic</string>
	<key>uploadSymbols</key>
	<true/>
	<key>destination</key>
	<string>upload</string>
</dict>
</plist>
PLISTEOF

    green "Generated: $EXPORT_PLIST"
}

# ── Write .env file ─────────────────────────────────────────────────

write_env() {
    cat > "$ENV_FILE" <<ENVEOF
# ── User Identity ──
HD_USER_ID=${HD_USER_ID}

# ── AWS ──
HD_AWS_REGION=${HD_AWS_REGION}
HD_DASHBOARD_AUTH_USER=${HD_DASHBOARD_AUTH_USER}
HD_DASHBOARD_AUTH_PASS=${HD_DASHBOARD_AUTH_PASS}

# ── iOS / Apple Developer ──
HD_BUNDLE_ID=${HD_BUNDLE_ID}
HD_DEVELOPMENT_TEAM=${HD_DEVELOPMENT_TEAM}
HD_ASC_KEY_ID=${HD_ASC_KEY_ID}

# ── API (auto-populated by setup.sh --post-deploy) ──
HD_API_BASE_URL=${HD_API_BASE_URL}
ENVEOF

    green "Saved: $ENV_FILE"
}

# ── Mode: --post-deploy ─────────────────────────────────────────────

post_deploy() {
    echo ""
    blue "Post-deploy mode: reading API URL from deploy config"
    echo ""

    [[ -f "$ENV_FILE" ]] || die ".env not found. Run ./setup.sh first."
    load_env

    [[ -f "$DEPLOY_CONFIG" ]] || die "No deploy config at $DEPLOY_CONFIG. Run deploy scripts first."
    source "$DEPLOY_CONFIG"

    if [[ -z "${MCP_FUNC_URL:-}" ]]; then
        die "MCP_FUNC_URL not set in .deploy-config. Run deploy-mcp.sh first."
    fi

    # Strip trailing slash if present
    HD_API_BASE_URL="${MCP_FUNC_URL%/}"
    validate_url "$HD_API_BASE_URL"

    # Update .env
    write_env

    # Regenerate xcconfig with the API URL
    generate_xcconfig "$HD_BUNDLE_ID" "$HD_DEVELOPMENT_TEAM" "$HD_API_BASE_URL" "$HD_USER_ID"

    echo ""
    green "Post-deploy setup complete!"
    blue "API URL: $HD_API_BASE_URL"
    blue "Rebuild the iOS app in Xcode to pick up the new URL."
}

# ── Mode: Interactive ────────────────────────────────────────────────

interactive() {
    echo ""
    echo "╭──────────────────────────────────────────╮"
    echo "│  Health Dashboard — Setup                 │"
    echo "╰──────────────────────────────────────────╯"
    echo ""

    # Load existing values as defaults
    load_env

    prompt HD_USER_ID           "User ID (your name/handle)" "${HD_USER_ID:-}"
    prompt HD_AWS_REGION        "AWS region"                  "${HD_AWS_REGION:-eu-west-2}"
    prompt HD_DASHBOARD_AUTH_USER "Dashboard auth username"   "${HD_DASHBOARD_AUTH_USER:-}"
    prompt HD_DASHBOARD_AUTH_PASS "Dashboard auth password"   "${HD_DASHBOARD_AUTH_PASS:-}"

    if [[ "$HD_DASHBOARD_AUTH_PASS" == "CHANGE_ME" ]]; then
        die "Please set a real password (not CHANGE_ME)"
    fi

    prompt HD_BUNDLE_ID         "iOS bundle ID"               "${HD_BUNDLE_ID:-com.yourcompany.healthdashboard}"
    prompt HD_DEVELOPMENT_TEAM  "Apple Developer Team ID"     "${HD_DEVELOPMENT_TEAM:-}"
    validate_team_id "$HD_DEVELOPMENT_TEAM"

    prompt HD_ASC_KEY_ID        "App Store Connect Key ID (or 'none')" "${HD_ASC_KEY_ID:-none}"

    # API URL is optional at initial setup (filled by --post-deploy)
    HD_API_BASE_URL="${HD_API_BASE_URL:-}"
    if [[ -n "$HD_API_BASE_URL" ]]; then
        printf "API base URL [%s]: " "$HD_API_BASE_URL"
        read -r api_input
        HD_API_BASE_URL="${api_input:-$HD_API_BASE_URL}"
    else
        printf "API base URL (leave empty — run --post-deploy after deploying): "
        read -r api_input
        HD_API_BASE_URL="${api_input:-}"
    fi

    if [[ -n "$HD_API_BASE_URL" ]]; then
        validate_url "$HD_API_BASE_URL"
    fi

    # ── Write files ──────────────────────────────────────────────────
    echo ""
    write_env
    generate_xcconfig "$HD_BUNDLE_ID" "$HD_DEVELOPMENT_TEAM" "$HD_API_BASE_URL" "$HD_USER_ID"
    generate_export_plist "$HD_DEVELOPMENT_TEAM"

    echo ""
    green "Setup complete!"
    echo ""
    blue "Next steps:"
    blue "  1. Deploy AWS infrastructure:  cd aws-deploy && ./deploy.sh"
    blue "  2. After deploying MCP Lambda: ./setup.sh --post-deploy"
    blue "  3. Open Xcode and build — no manual config needed"
}

# ── Main ─────────────────────────────────────────────────────────────

case "${1:-}" in
    --post-deploy) post_deploy ;;
    *)             interactive ;;
esac
